### ISSUE TITLE
Format problem in MISC field 

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/UD_Irish-TwittIrish#1]
In the 3 tokens below, the MISC field seems to be wrongly formatted:

* https://github.com/UniversalDependencies/UD_Irish-TwittIrish/blob/1271b866929544cc7c6a88d97a71f81dd06bc2bb/ga_twittirish-ud-test.conllu#L2890 &rarr; a `|` is missing before `CSType` 

* https://github.com/UniversalDependencies/UD_Irish-TwittIrish/blob/1271b866929544cc7c6a88d97a71f81dd06bc2bb/ga_twittirish-ud-test.conllu#L3406 &rarr; two consecutive `|`

* https://github.com/UniversalDependencies/UD_Irish-TwittIrish/blob/1271b866929544cc7c6a88d97a71f81dd06bc2bb/ga_twittirish-ud-test.conllu#L4808 &rarr; two consecutive `|`

**Comment by dan-zeman** [comment]
@laurenCassidy : Should I fix these in the dev branch? If we act quickly, the fix can still be included in UD 2.8.

**Comment by laurenCassidy** [comment]
Yes please!

**Comment by dan-zeman** [comment]
OK, done.
